<?php
/**
 * Implements hook_block_info().
 */
function coconuts_feature_block_info() {

  $blocks['feature_videos_brightcove'] = array(
    'info' => t('Block Feature Videos Brightcove'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function coconuts_feature_block_view($delta = '') {
  $block = array();

  switch ($delta) {

    case 'feature_videos_brightcove':
      $block['subject'] = t('Feature videos brightcove');
      $block['content'] = array(
        '#theme' => 'featurevideos__block_brightcove',
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function coconuts_feature_theme($existing, $type, $theme, $path) {
  return array(
    'featurevideos__block_brightcove' => array(
      'template' => 'featurevideos__block__brightcove',
      'variables' => array(),
    ),
  );
}
